
package lab1.standalone.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FilmService", targetNamespace = "http://services.standalone.lab1/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FilmService {


    /**
     * 
     * @param duration
     * @param country
     * @param director
     * @param dateOfStart
     * @param filmName
     * @return
     *     returns java.util.List<lab1.standalone.services.Film>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFilmsByFields", targetNamespace = "http://services.standalone.lab1/", className = "lab1.standalone.services.GetFilmsByFields")
    @ResponseWrapper(localName = "getFilmsByFieldsResponse", targetNamespace = "http://services.standalone.lab1/", className = "lab1.standalone.services.GetFilmsByFieldsResponse")
    @Action(input = "http://services.standalone.lab1/FilmService/getFilmsByFieldsRequest", output = "http://services.standalone.lab1/FilmService/getFilmsByFieldsResponse")
    public List<Film> getFilmsByFields(
        @WebParam(name = "filmName", targetNamespace = "")
        String filmName,
        @WebParam(name = "director", targetNamespace = "")
        String director,
        @WebParam(name = "country", targetNamespace = "")
        String country,
        @WebParam(name = "dateOfStart", targetNamespace = "")
        XMLGregorianCalendar dateOfStart,
        @WebParam(name = "duration", targetNamespace = "")
        Double duration);

}
